on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello,\nyour report will be looked into as soon as possible.\nPlease do not bump this thread and don't post it on multiple platforms."
          footer: "Thanks a lot for your patience."
